import Head from "next/head";
import { Text } from "@/components/ui/text";
import { View } from "react-native";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="p-4 flex flex-row gap-4">
          <View className="p-4 rounded-md border">
            <Text>This border should not be black.</Text>
          </View>
        </div>
      </main>
    </>
  );
}
